### PR TITLE
Test showing synchronous partition(timeout) + dask scatter is broken

### PR DESCRIPTION
**Pull request by wwoods**
The output for this failing test shows, `ValueError: Two different event loops active`. Basically, the new `partition(timeout=...)` functionality doesn't play well with synchronous dask streams.

### CODE REVIEW

**Comment by martindurant** [comment]
I think you either have to create the dask client first and pass its `.loop` to the source
```
source = Stream(asynchronous=True, loop=c.loop)
```

DaskStream checks for a client and uses its loop, but I think it happens too late here, the source will already have created a loop. 
```
    def __init__(self, *args, **kwargs):
        if 'loop' not in kwargs:
            kwargs['loop'] = default_client().loop
        super(DaskStream, self).__init__(*args, **kwargs)
```
Perhaps the test for default_client() should be done in core.get_io_loop?

**Comment by wwoods** [comment]
I see. Avoiding manual loop passing wherever possible would certainly simplify usage, and would better follow the Dask convention for client.

If the `distributed.client` import were wrapped s.t. it tolerates an `ImportError`, and that's OK to include in `core.py`, then trying `default_client` first in `core.get_io_loop` might streamline the user experience.

To this end, I've pushed a commit which I think addresses the issue, but clearly something isn't quite right since the tests don't pass. Anyway, putting this down for now.

**Comment by wwoods** [comment]
Replying to @martindurant 's comment on #400 , since this is the open PR with a better description of the issue.

Perhaps the biggest oddity about removing synchronous calls in Streamz would be that Streamz itself doesn't really support asynchronous operations. The async computation looks like it's only used to prop up other functionality. For example, if I wanted an asynchronous computation in `map`, it doesn't look like Streamz supports this at the moment.

**Comment by martindurant** [comment]
There are a few places where we check a function to see if it's awaitable (i.e., a coroutine object, after being called), and indeed it would make sense to use this sort of logic wherever a callable is required by the API. Again, we should probably have a firm idea of exactly what we support.

**Comment by martindurant** [comment]
So, I think we do still need to force the dask stream to fetch its IO loop - otherwise it doesn't run at all. I wonder what would happen if it was instantiated *before* the dask client, would we get two even loops?

**Comment by martindurant** [comment]
If you don't mind, I'll still push some small changes here to squash most of the warnings we see

**Comment by wwoods** [comment]
Yeah push whatever you want here -- I actually didn't realize GitHub allowed commits on PRs outside of the repository providing the base PR branch.

The dask client is running its IO loop in a separate thread, it just breaks in the tests for some reason. If you try the code I submitted with a custom script, it works fine. E.g., this does what you'd expect:

```python
            s = streamz.Stream()
            L = s.partition(2, timeout=1.).scatter().map(lambda x: [xx+1 for xx in x]).buffer(8).gather().flatten().sink_to_list()
            s.emit(1)
            s.emit(2)
            s.emit(3)
            time.sleep(3)
            print(L)
```

**Comment by wwoods** [comment]
Awesome, thanks for finishing this up! Much appreciated.

**Pull request merged**
