### PR TITLE
fix: is_dataframe_like compatibility with pandas.DataFrame v1.1

### LINKED ISSUE #346: Stop using the presence of `value_counts` to determine that an object is not a pandas.DataFrame
From version 1.1 the `pandas.DataFrame` contains `value_counts` so the https://github.com/python-streamz/streamz/blob/de166a40babc9690be17d1b92dcd64fa5e149362/streamz/dataframe/utils.py#L7 doesn't work.

see an issue in dask - https://github.com/dask/dask/issues/5109

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html

### PR DESCRIPTION
**Pull request by bednar**
Closes #346 

Fixed checking of DataFrame for pandas 1.1+.

### CODE REVIEW

**Comment by bednar** [comment]
The https://github.com/python-streamz/streamz/blob/de166a40babc9690be17d1b92dcd64fa5e149362/streamz/dataframe/tests/test_dataframes.py#L782 should be updated, because currently is not compatible with panda.DataFrame v1.1

**Comment by martindurant** [comment]
> should be updated

Do you intend to do this?

**Comment by bednar** [comment]
Nope, I tried it but it is over my capabilities :(

**Comment by martindurant** [comment]
Fix was merged in #348 , including for series and index. OK to close here?

**Comment by bednar** [comment]
Yes, thanks for Fix.

**Pull request closed without merging**
