### PR TITLE
remove six dependency

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by martindurant** [comment]
You will need to make the 311, 312 env files, sorry. Yes, of course this should be templated :|

**Comment by a-detiste** [comment]
Hi, I don't mind, it's fun learning new things

**Comment by a-detiste** [comment]
It's getting interresting

**Comment by martindurant** [comment]
Entrypoints changed its API at some point. The section of code dealing with that will need a version check.

Intake has:
```
from importlib.metadata import entry_points

...
    eps = entry_points()
    if hasattr(eps, "select"):  # Python 3.10+ / importlib_metadata >= 3.9.0
        specs = eps.select(group="intake.imports")
    else:
        specs = eps.get("intake.imports", [])
```

**Comment by a-detiste** [comment]
pig

**Comment by martindurant** [comment]
Sorry, I didn't notice the new commit :|

**Pull request merged**
