### PR TITLE
Add backpressure test

### PR DESCRIPTION
**Pull request by martindurant**
Ref #378 

@roveo - how is this example different from yours? This passes.

### CODE REVIEW

**Comment by roveo** [comment]
- My guess is, the part of the pipeline that applies backpressure to the source (rate_limit) is built by method chaining. There's no `Source()` node in the middle, so everything works OK, and this affects `sout` too.
- If you change the `Stream.update` method

https://github.com/python-streamz/streamz/blob/e9a25452ca13af5ca0edf3346f8c67353d291501/streamz/core.py#L450-L453

to be a coroutine:

```py
    @gen.coroutine
    def update(self, x, who=None, metadata=None):
        yield self._emit(x, metadata=metadata)
```

then my test example passes too.

**Comment by roveo** [comment]
OK, so here's a log of calls with `time.time()` from my example:

```
1604961709.142924 from_list.emit 0
1604961709.1429608 Stream.update 0
1604961709.1429892 rate_limit.update 0
1604961709.143005 sink 0
1604961709.1431391 from_list.emit 1
1604961709.1431592 Stream.update 1
1604961709.143174 rate_limit.update 1
1604961709.1433449 from_list.emit 2
1604961709.1433642 Stream.update 2
1604961709.143379 rate_limit.update 2
1604961709.143423 from_list.emit 3
1604961709.143439 Stream.update 3
1604961709.143453 rate_limit.update 3
1604961709.1434932 from_list.emit 4
1604961709.143507 Stream.update 4
1604961709.14352 rate_limit.update 4

AssertionError  # from the test (source list is empty). At this point we have 4 instances of rate_limit.update running.

1604961710.145355 sink 1
1604961711.1437702 sink 2
1604961712.144693 sink 3
1604961713.147051 sink 4
```

And here's the same thing, but with `Stream.update` a coroutine:

```
1604961822.514569 from_list.emit 0
1604961822.514626 Stream.update 0
1604961822.514658 rate_limit.update 0
1604961822.514681 sink 0
1604961822.515048 from_list.emit 1
1604961822.515075 Stream.update 1
1604961822.515093 rate_limit.update 1
1604961823.5194051 sink 1
1604961823.519525 from_list.emit 2
1604961823.519547 Stream.update 2
1604961823.519562 rate_limit.update 2
1604961824.5165849 sink 2
1604961824.516799 from_list.emit 3
1604961824.516845 Stream.update 3
1604961824.5168781 rate_limit.update 3
1604961825.518817 sink 3
1604961825.5191329 from_list.emit 4
1604961825.519197 Stream.update 4
1604961825.5192409 rate_limit.update 4
1604961826.519273 sink 4
```

As you can see, in the first instance `rate_limit.update` gets called 5 times immediately, and then these running coroutines return each second.

**Comment by martindurant** [comment]
I assume that the change would break things elsewhere? Or do you have the whole test suite passing too?

**Comment by roveo** [comment]
> do you have the whole test suite passing
Almost everything passes locally, but it gets stuck at 98% somewhere in Kafka tests. Core, dataframes etc. are ok.

**Comment by martindurant** [comment]
Sorry, this one got lost
(thanks for pushing on this and other progress in this repo!)

For some reason, this tests didn't run (ref #387 ), can you please kick it?

**Comment by roveo** [comment]
I don't think I can, this is your PR :)

**Comment by martindurant** [comment]
oops :) I suppose we should have a new PR with this test, or something like it, plus the coroutine change, so that we are talking about the same thing.

**Comment by roveo** [comment]
Created #390

**Pull request closed without merging**
