### PR TITLE
bump for release

### LINKED ISSUE #435: 0.6.3 Release
Would it be possible to do a release of streamz 0.6.3 ?  We are seeing some failures @galipremsagar resolved in https://github.com/python-streamz/streamz/commit/59f0f987f39adca2131f8d3726caec7ea8160bce .  If folks are busy I'd be happy to help

### PR DESCRIPTION
**Pull request by martindurant**
Thanks for the ping, @quasiben

Fixes #435

We don't seem to have a changelog - is there anything more than the version numbers that need to be changed?

### CODE REVIEW

**Comment by quasiben** [comment]
I'm not aware of anything. Thanks for the quick reply!

**Comment by martindurant** [comment]
On PyPI now

**Comment by quasiben** [comment]
Will conda-forge also get automagically created ?

**Comment by martindurant** [comment]
Yes, but it will take the bot some time, unless someone wants to make the PR manually. I don't normally bother.

**Comment by ajschmidt8** [comment]
feedstock PR opened here: https://github.com/conda-forge/streamz-feedstock/pull/18

**Pull request merged**
