### PR TITLE
Multiple topic partitions

### PR DESCRIPTION
**Pull request by martindurant**
@chinmaychandak - I started this, because your pull request is from master branch, so I won't push to it.

### CODE REVIEW

**Comment by martindurant** [comment]
Note: the CI has pinnings libdrkafka=1.2.2, python-confluent-kafka=1.1.0. I suggest dropping these pinnings, as they are rather old. 

@chinmaychandak , were you using these versions or newer for your various benchmarks?

**Comment by chinmaychandak** [comment]
Thanks for creating this, @martindurant! Is it okay if I push a few more changes to the tests using `wait_for` to your branch? 

> were you using these versions or newer for your various benchmarks?

I was using the latest versions of both for benchmarking.

**Comment by chinmaychandak** [comment]
Created https://github.com/martindurant/streamz/pull/1.

**Comment by martindurant** [comment]
I don't mind where it ends up - either pull my commits, PR to my branch or make your PR from a branch so I can push to it.

**Comment by martindurant** [comment]
Closes #367

**Pull request merged**
