### PR TITLE
Tests for rolling aggregations in cudf.

### PR DESCRIPTION
**Pull request by chinmaychandak**
Some features are not yet available w.r.t. rolling objects in cudf. Will update the tests once the features are rolled out.

### CODE REVIEW

**Comment by chinmaychandak** [comment]
This seems to failing on a test that wasn't modified. Could someone please check?

**Comment by martindurant** [comment]
Yes, appears to be due to pandas 0.25. Do you think you can fix it?

**Comment by chinmaychandak** [comment]
Made the fix, hope this works out.

**Comment by chinmaychandak** [comment]
@martindurant Some other error unrelated to the PR popped up, I guess.

**Comment by martindurant** [comment]
Please check on distributed what the correct call to gen_cluster should look like.

**Comment by chinmaychandak** [comment]
I don't think I modified that test. It seems to be a Dask-related test. I'll try looking into it, although I'm not sure I have enough knowledge to fix it.

**Comment by martindurant** [comment]
Right - it will be because the upstream signature changed in the meantime.

**Comment by chinmaychandak** [comment]
@martindurant Made the fixes. Could you please take a look?

Also, it would be great to have the cudf integration using `conda install -c conda-forge streamz`. Could one of the maintainers please update the Anaconda package; I think it is outdated w.r.t. the cudf changes?

**Comment by martindurant** [comment]
Hoping to make a release soon

**Comment by martindurant** [comment]
https://github.com/conda-forge/streamz-feedstock/pull/9

**Comment by chinmaychandak** [comment]
Awesome, thanks!

**Pull request merged**
