### PR TITLE
Add docs and examples for cudf support

### PR DESCRIPTION
**Pull request by skmatti**
This adds code documentation and notebook examples for streaming cudf dataframes using Streamz DataFrame.

### CODE REVIEW

**Comment by skmatti** [comment]
This is failing with Python2.7 but not sure if the failure is due to this PR.

**Comment by martindurant** [comment]
For py2, it may be worth pinning to an earlier version of distributed - there will be some non-py2 usages creeping into that codebase.

**Comment by martindurant** [comment]
Please merge from master - py2 will no longer be tested at all, so this should then pass.

**Comment by skmatti** [comment]
Yes! it's green.

**Pull request merged**
