### PR TITLE
Pieces that occurred while working on intake-streamz

### PR DESCRIPTION
**Pull request by martindurant**
https://github.com/intake/intake-streamz coming soon

Changes:
- a `current_value` attribute that holds the most recently emitted thing from a stream (and is *not* part of reference counting, but very useful for introspection)
- make API registering a mixin and apply to `DataFrame`, with only one method right now: `from_periodic`
- add `start` and `stop` methods to `DataFrame`, and make these actions work wherever in a pipeline they are called

### CODE REVIEW

**Comment by martindurant** [comment]
Note that is we have `@DataFrame.register_api`, then we can also have this type of entry point

**Comment by martindurant** [comment]
@roveo , what do you think of from_* methods on dataframes, and an entrypoints category for them? At the moment there is only one, `from_periodic` (plus maybe a counterpart to `Random`, which is just a special case).

**Comment by martindurant** [comment]
@chinmaychandak @CJ-Wright , I thought you might find the changes here generally interesting.

**Comment by chinmaychandak** [comment]
Excellent! Thanks for adding this :)

**Comment by roveo** [comment]
> what do you think of from_* methods on dataframes, and an entrypoints category for them?

I only work with core day-to-day, so what's currently supported by plugins is in no way exhaustive. If there's a need for DataFrame sources in plugins (and nodes, and possibly sinks?), then sure, let's support them.

**Pull request merged**
