### PR TITLE
RiverML: update the plots less frequently

### PR DESCRIPTION
**Pull request by maximlt**
Instead of using `hvplot` I've directly used `holoviews` and `DynamicMap`s and `Pipe`s. I've partitioned the observations and clusters and concatenated them to send them only every X events. Running the script with `viz=True` I get a refresh rate of about 50 Hz for a cadence of 100 Hz, while I get an output at about 70 Hz without any viz (same cadence).

### CODE REVIEW

**Comment by martindurant** [comment]
Thanks very much, good to see! We should make this example more prominent, right?

**Comment by maximlt** [comment]
Yes why not! It's an interesting and powerful application of streamz+holoviews. The question is, where? @jbednar any recommendation? This is what the example looks like (running the `river_kmeans.py` script with `viz=True`):

riverml_streamz_example

**Comment by jbednar** [comment]
Maybe link from examples.pyviz?

**Comment by maximlt** [comment]
Maybe this should just be a proper example on examples.pyviz.org

@martindurant would you be interested in writing a notebook that introduces streamz and its support of RiverML, and the example (online k-means clustering)? If so, I could take care of polishing the plot and publishing the example on examples.pyviz.org (creating the anaconda-project and deploying it on AE5).

**Pull request merged**
