### PR TITLE
Display in notebook without ipywidgets

### LINKED ISSUE #410: Informative repr for streamz when ipywidgets is not installed
Currently if the user does not have `ipywidgets` installed then running something like the following in a notebook produces no output

```python
import streamz.dataframe
df = streamz.dataframe.Random()
df.tail()
```

It might be nicer to include a message encouraging users to install ipywidgets in this case.

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #410

### CODE REVIEW

**Comment by martindurant** [comment]
@chinmaychandak - are you aware of anything changing with kafka ? We seem to have a consistent failure here.

**Comment by chinmaychandak** [comment]
This seems to be some kind of timing issue: https://github.com/python-streamz/streamz/pull/411/checks?check_run_id=2151820531#step:6:1617.  

Somehow streamz ended up reading multiple messages in a batch as opposed to just one; this should never have happened because there's a `sleep(2)` in place after flushing every new message to Kafka which is more than the poll interval b/w batches. We could add `max_batch_size=1`, or maybe try increasing sleep time.

I'm wondering why it worked with Py3.7, should we just rerun? Hesitant to add `flaky` here.

**Comment by martindurant** [comment]
I did rerun a couple of times with the same result. I can't think why the two versions would be different either.

**Comment by martindurant** [comment]
> this should never have happened because there's a sleep(2) in place after flushing every new message to Kafka 

Could it be that kafka (the broker or the driver, who knows) is just that slow in this CI setup?

**Comment by chinmaychandak** [comment]
> > this should never have happened because there's a sleep(2) in place after flushing every new message to Kafka
> 
> Could it be that kafka (the broker or the driver, who knows) is just that slow in this CI setup?

Definitely possible! In this case, we should just increase sleep time. Sorry, I'm in IST currently, so replied will be timed accordingly.

**Comment by martindurant** [comment]
@chinmaychandak if you have the time, would like to see that test fixed. I don't love the sleep() option, but if it's the only way...

**Pull request merged**
